/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Asteroid() {
  const group = useRef()
  const { nodes, materials } = useGLTF('/aster.glb')
  return (
    <group ref={group} dispose={null} scale={0.1} position={[20,0,0]} >
      <group position={[-38.03, -49.16, 98.04]} rotation={[-2.39, 0.21, 0.22]} scale={0.07}>
        <group position={[-55.41, -51.04, -46.26]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials['Default.004']} position={[-24.2, -2.59, -5.48]} rotation={[-0.06, -0.03, 0.22]} />
          <mesh geometry={nodes.Object_2002.geometry} material={materials['Default.004']} position={[0.11, -101.42, -102.98]} />
          <mesh geometry={nodes.Object_2003.geometry} material={materials['Default.004']} position={[-56.07, -223.59, -98.93]} rotation={[-1.63, 0.32, 2.17]} />
          <mesh geometry={nodes.Object_2004.geometry} material={materials['Default.004']} position={[-142.43, -292.97, 3.37]} rotation={[-0.13, -0.51, -2.04]} />
          <mesh geometry={nodes.Object_2005.geometry} material={materials['Default.004']} position={[79.95, 52.27, -124.86]} rotation={[-0.29, 0.1, 1.02]} />
          <mesh geometry={nodes.Object_2006.geometry} material={materials['Default.004']} position={[22.5, 134.06, 47.04]} rotation={[-1.04, -0.66, -1.4]} />
          <mesh geometry={nodes.Object_2007.geometry} material={materials['Default.004']} position={[-108.48, -54.65, 134.44]} rotation={[-0.32, 0.51, 1.14]} />
          <mesh geometry={nodes.Object_2008.geometry} material={materials['Default.004']} position={[-170.96, -202.7, 129.03]} rotation={[-1.23, -0.64, -1.55]} />
          <mesh geometry={nodes.Object_2009.geometry} material={materials['Default.004']} position={[-88.8, -389.69, -173.64]} rotation={[-0.76, -0.6, -1.35]} />
          <mesh geometry={nodes.Object_2010.geometry} material={materials['Default.004']} position={[38.33, -218.69, -268.35]} rotation={[-0.12, -0.2, -1.17]} />
          <mesh geometry={nodes.Object_2011.geometry} material={materials['Default.004']} position={[101.68, -44.01, -242.92]} rotation={[0.31, -0.01, -0.67]} />
          <mesh geometry={nodes.Object_2012.geometry} material={materials['Default.004']} position={[116.79, 219.22, -57.01]} rotation={[-0.69, -0.74, -0.47]} />
        </group>
      </group>
      <group position={[-40.39, -40.25, 104.25]} rotation={[-2.39, 0.21, 0.22]} scale={0.07}>
        <group position={[-55.41, -51.04, -46.26]}>
          <mesh geometry={nodes.Object_2001.geometry} material={materials['Default.004']} position={[-18.72, -29.85, -10.28]} rotation={[-0.06, -0.37, -1.12]} />
        </group>
      </group>
      <group position={[-10.21, -71.93, 60.97]} rotation={[-Math.PI / 2, 0, 0]} scale={0.07}>
        <group position={[-55.41, -51.04, -46.26]}>
          <mesh geometry={nodes.Object_2013.geometry} material={materials['Default.004']} position={[-24.2, -2.59, -5.48]} rotation={[-0.06, -0.03, 0.22]} />
          <mesh geometry={nodes.Object_2015.geometry} material={materials['Default.004']} position={[0.11, -101.42, -102.98]} />
          <mesh geometry={nodes.Object_2016.geometry} material={materials['Default.004']} position={[-56.07, -223.59, -98.93]} rotation={[-1.63, 0.32, 2.17]} />
          <mesh geometry={nodes.Object_2017.geometry} material={materials['Default.004']} position={[-142.43, -323.8, -29.28]} rotation={[-0.28, -0.51, -2.04]} />
          <mesh geometry={nodes.Object_2018.geometry} material={materials['Default.004']} position={[79.95, 52.27, -124.86]} rotation={[-0.29, 0.1, 1.02]} />
          <mesh geometry={nodes.Object_2019.geometry} material={materials['Default.004']} position={[22.5, 134.06, 47.04]} rotation={[-1.04, -0.66, -1.4]} />
          <mesh geometry={nodes.Object_2020.geometry} material={materials['Default.004']} position={[-108.48, -54.65, 134.44]} rotation={[-0.32, 0.51, 1.14]} />
          <mesh geometry={nodes.Object_2021.geometry} material={materials['Default.004']} position={[-170.96, -202.7, 129.03]} rotation={[-1.23, -0.64, -1.55]} />
          <mesh geometry={nodes.Object_2022.geometry} material={materials['Default.004']} position={[-88.8, -389.69, -173.64]} rotation={[-0.76, -0.6, -1.35]} />
          <mesh geometry={nodes.Object_2023.geometry} material={materials['Default.004']} position={[38.33, -218.69, -268.35]} rotation={[-0.12, -0.2, -1.17]} />
          <mesh geometry={nodes.Object_2024.geometry} material={materials['Default.004']} position={[101.68, -44.01, -242.92]} rotation={[0.31, -0.01, -0.67]} />
          <mesh geometry={nodes.Object_2025.geometry} material={materials['Default.004']} position={[116.79, 219.22, -57.01]} rotation={[-0.69, -0.74, -0.47]} />
          <mesh geometry={nodes.Object_2052.geometry} material={materials['Default.004']} position={[365.98, 1569.35, 154.84]} rotation={[0.19, -0.66, 0.01]} />
        </group>
      </group>
      <group position={[-15.15, -70.91, 70.87]} rotation={[-Math.PI / 2, 0, 0]} scale={0.07}>
        <group position={[-55.41, -51.04, -46.26]}>
          <mesh geometry={nodes.Object_2014.geometry} material={materials['Default.004']} position={[-18.72, -29.85, -10.28]} rotation={[-0.04, -0.37, -1.12]} />
        </group>
      </group>
      <group position={[8.98, -91.95, 16.79]} rotation={[-1.02, -0.05, 0.24]} scale={0.07}>
        <group position={[-55.41, -51.04, -46.26]}>
          <mesh geometry={nodes.Object_2026.geometry} material={materials['Default.004']} position={[-24.2, -2.59, -5.48]} rotation={[-0.06, -0.03, 0.22]} />
          <mesh geometry={nodes.Object_2028.geometry} material={materials['Default.004']} position={[0.11, -101.42, -102.98]} />
          <mesh geometry={nodes.Object_2029.geometry} material={materials['Default.004']} position={[-56.07, -223.59, -98.93]} rotation={[-1.63, 0.32, 2.17]} />
          <mesh geometry={nodes.Object_2030.geometry} material={materials['Default.004']} position={[-142.43, -292.97, 3.37]} rotation={[-0.13, -0.51, -2.04]} />
          <mesh geometry={nodes.Object_2031.geometry} material={materials['Default.004']} position={[79.95, 52.27, -124.86]} rotation={[-0.29, 0.1, 1.02]} />
          <mesh geometry={nodes.Object_2032.geometry} material={materials['Default.004']} position={[22.5, 134.06, 47.04]} rotation={[-1.04, -0.66, -1.4]} />
          <mesh geometry={nodes.Object_2033.geometry} material={materials['Default.004']} position={[-108.48, -54.65, 134.44]} rotation={[-0.32, 0.51, 1.14]} />
          <mesh geometry={nodes.Object_2034.geometry} material={materials['Default.004']} position={[-170.96, -202.7, 129.03]} rotation={[-1.23, -0.64, -1.55]} />
          <mesh geometry={nodes.Object_2035.geometry} material={materials['Default.004']} position={[-88.8, -389.69, -173.64]} rotation={[-0.76, -0.6, -1.35]} />
          <mesh geometry={nodes.Object_2036.geometry} material={materials['Default.004']} position={[38.33, -218.69, -268.35]} rotation={[-0.12, -0.2, -1.17]} />
          <mesh geometry={nodes.Object_2037.geometry} material={materials['Default.004']} position={[101.68, -44.01, -242.92]} rotation={[0.31, -0.01, -0.67]} />
          <mesh geometry={nodes.Object_2038.geometry} material={materials['Default.004']} position={[116.79, 219.22, -57.01]} rotation={[-0.69, -0.74, -0.47]} />
        </group>
      </group>
      <group position={[6.52, -96.84, 26.47]} rotation={[-1.02, -0.05, 0.24]} scale={0.07}>
        <group position={[-55.41, -51.04, -46.26]}>
          <mesh geometry={nodes.Object_2027.geometry} material={materials['Default.004']} position={[-18.72, -29.85, -10.28]} rotation={[-0.04, -0.37, -1.12]} />
        </group>
      </group>
      <group position={[22.96, -79.64, -37.22]} rotation={[-1.02, -0.05, 0.24]} scale={0.07}>
        <group position={[-55.41, -51.04, -46.26]}>
          <mesh geometry={nodes.Object_2039.geometry} material={materials['Default.004']} position={[-24.2, -2.59, -5.48]} rotation={[-0.06, -0.03, 0.22]} />
          <mesh geometry={nodes.Object_2041.geometry} material={materials['Default.004']} position={[0.11, -101.42, -102.98]} />
          <mesh geometry={nodes.Object_2042.geometry} material={materials['Default.004']} position={[-56.07, -223.59, -98.93]} rotation={[-1.63, 0.32, 2.17]} />
          <mesh geometry={nodes.Object_2043.geometry} material={materials['Default.004']} position={[-142.43, -292.97, 3.37]} rotation={[-0.13, -0.51, -2.04]} />
          <mesh geometry={nodes.Object_2044.geometry} material={materials['Default.004']} position={[79.95, 52.27, -124.86]} rotation={[-0.29, 0.1, 1.02]} />
          <mesh geometry={nodes.Object_2045.geometry} material={materials['Default.004']} position={[22.5, 134.06, 47.04]} rotation={[-1.04, -0.66, -1.4]} />
          <mesh geometry={nodes.Object_2046.geometry} material={materials['Default.004']} position={[-108.48, -54.65, 134.44]} rotation={[-0.32, 0.51, 1.14]} />
          <mesh geometry={nodes.Object_2047.geometry} material={materials['Default.004']} position={[-170.96, -202.7, 129.03]} rotation={[-1.23, -0.64, -1.55]} />
          <mesh geometry={nodes.Object_2048.geometry} material={materials['Default.004']} position={[-88.8, -389.69, -173.64]} rotation={[-0.76, -0.6, -1.35]} />
          <mesh geometry={nodes.Object_2049.geometry} material={materials['Default.004']} position={[38.33, -218.69, -268.35]} rotation={[-0.12, -0.2, -1.17]} />
          <mesh geometry={nodes.Object_2050.geometry} material={materials['Default.004']} position={[101.68, -44.01, -242.92]} rotation={[0.31, -0.01, -0.67]} />
          <mesh geometry={nodes.Object_2051.geometry} material={materials['Default.004']} position={[116.79, 219.22, -57.01]} rotation={[-0.69, -0.74, -0.47]} />
        </group>
      </group>
      <group position={[20.5, -84.53, -27.55]} rotation={[-1.02, -0.05, 0.24]} scale={0.07}>
        <group position={[-55.41, -51.04, -46.26]}>
          <mesh geometry={nodes.Object_2040.geometry} material={materials['Default.004']} position={[-18.72, -29.85, -10.28]} rotation={[-0.04, -0.37, -1.12]} />
        </group>
      </group>
      <group position={[15.06, -57.96, -88.34]} rotation={[-0.47, 0.3, 0.35]} scale={0.07}>
        <group position={[-55.41, -51.04, -46.26]}>
          <mesh geometry={nodes.Object_2053.geometry} material={materials['Default.004']} position={[-24.2, -2.59, -5.48]} rotation={[-0.06, -0.03, 0.22]} />
          <mesh geometry={nodes.Object_2055.geometry} material={materials['Default.004']} position={[0.11, -101.42, -102.98]} />
          <mesh geometry={nodes.Object_2056.geometry} material={materials['Default.004']} position={[-56.07, -223.59, -98.93]} rotation={[-1.63, 0.32, 2.17]} />
          <mesh geometry={nodes.Object_2057.geometry} material={materials['Default.004']} position={[-142.43, -292.97, 3.37]} rotation={[-0.13, -0.51, -2.04]} />
          <mesh geometry={nodes.Object_2058.geometry} material={materials['Default.004']} position={[79.95, 52.27, -124.86]} rotation={[-0.29, 0.1, 1.02]} />
          <mesh geometry={nodes.Object_2059.geometry} material={materials['Default.004']} position={[22.5, 134.06, 47.04]} rotation={[-1.04, -0.66, -1.4]} />
          <mesh geometry={nodes.Object_2060.geometry} material={materials['Default.004']} position={[-108.48, -54.65, 134.44]} rotation={[-0.32, 0.51, 1.14]} />
          <mesh geometry={nodes.Object_2061.geometry} material={materials['Default.004']} position={[-170.96, -202.7, 129.03]} rotation={[-1.23, -0.64, -1.55]} />
          <mesh geometry={nodes.Object_2062.geometry} material={materials['Default.004']} position={[-88.8, -389.69, -173.64]} rotation={[-0.76, -0.6, -1.35]} />
          <mesh geometry={nodes.Object_2063.geometry} material={materials['Default.004']} position={[38.33, -218.69, -268.35]} rotation={[-0.12, -0.2, -1.17]} />
          <mesh geometry={nodes.Object_2064.geometry} material={materials['Default.004']} position={[101.68, -44.01, -242.92]} rotation={[0.31, -0.01, -0.67]} />
          <mesh geometry={nodes.Object_2065.geometry} material={materials['Default.004']} position={[116.79, 219.22, -57.01]} rotation={[-0.69, -0.74, -0.47]} />
        </group>
      </group>
      <group position={[14.17, -67.14, -82.15]} rotation={[-0.47, 0.3, 0.35]} scale={0.07}>
        <group position={[-55.41, -51.04, -46.26]}>
          <mesh geometry={nodes.Object_2054.geometry} material={materials['Default.004']} position={[-18.72, -29.85, -10.28]} rotation={[-0.04, -0.37, -1.12]} />
        </group>
      </group>
      <group position={[16.67, -18.6, -129.04]} rotation={[-0.21, 0.3, 0.35]} scale={0.07}>
        <group position={[-55.41, -51.04, -46.26]}>
          <mesh geometry={nodes.Object_2066.geometry} material={materials['Default.004']} position={[-24.2, -2.59, -5.48]} rotation={[-0.06, -0.03, 0.22]} />
          <mesh geometry={nodes.Object_2068.geometry} material={materials['Default.004']} position={[0.11, -101.42, -102.98]} />
          <mesh geometry={nodes.Object_2069.geometry} material={materials['Default.004']} position={[-56.07, -223.59, -98.93]} rotation={[-1.63, 0.32, 2.17]} />
          <mesh geometry={nodes.Object_2070.geometry} material={materials['Default.004']} position={[-142.43, -292.97, 3.37]} rotation={[-0.13, -0.51, -2.04]} />
          <mesh geometry={nodes.Object_2071.geometry} material={materials['Default.004']} position={[79.95, 52.27, -124.86]} rotation={[-0.29, 0.1, 1.02]} />
          <mesh geometry={nodes.Object_2072.geometry} material={materials['Default.004']} position={[22.5, 134.06, 47.04]} rotation={[-1.04, -0.66, -1.4]} />
          <mesh geometry={nodes.Object_2073.geometry} material={materials['Default.004']} position={[-108.48, -54.65, 134.44]} rotation={[-0.32, 0.51, 1.14]} />
          <mesh geometry={nodes.Object_2074.geometry} material={materials['Default.004']} position={[-170.96, -202.7, 129.03]} rotation={[-1.23, -0.64, -1.55]} />
          <mesh geometry={nodes.Object_2075.geometry} material={materials['Default.004']} position={[-88.8, -389.69, -173.64]} rotation={[-0.76, -0.6, -1.35]} />
          <mesh geometry={nodes.Object_2076.geometry} material={materials['Default.004']} position={[38.33, -218.69, -268.35]} rotation={[-0.12, -0.2, -1.17]} />
          <mesh geometry={nodes.Object_2077.geometry} material={materials['Default.004']} position={[101.68, -44.01, -242.92]} rotation={[0.31, -0.01, -0.67]} />
          <mesh geometry={nodes.Object_2078.geometry} material={materials['Default.004']} position={[116.79, 219.22, -57.01]} rotation={[-0.69, -0.74, -0.47]} />
        </group>
      </group>
      <group position={[15.77, -29.08, -125.44]} rotation={[-0.21, 0.3, 0.35]} scale={0.07}>
        <group position={[-55.41, -51.04, -46.26]}>
          <mesh geometry={nodes.Object_2067.geometry} material={materials['Default.004']} position={[-18.72, -29.85, -10.28]} rotation={[-0.04, -0.37, -1.12]} />
        </group>
      </group>
      <group position={[-20.69, 24.69, 107.66]} rotation={[2.65, 0.02, -2.39]} scale={0.07}>
        <group position={[-55.41, -51.04, -46.26]}>
          <mesh geometry={nodes.Object_2079.geometry} material={materials['Default.004']} position={[-24.2, -2.59, -5.48]} rotation={[-0.06, -0.03, 0.22]} />
          <mesh geometry={nodes.Object_2081.geometry} material={materials['Default.004']} position={[0.11, -101.42, -102.98]} />
          <mesh geometry={nodes.Object_2082.geometry} material={materials['Default.004']} position={[-56.07, -223.59, -98.93]} rotation={[-1.63, 0.32, 2.17]} />
          <mesh geometry={nodes.Object_2083.geometry} material={materials['Default.004']} position={[-142.43, -292.97, 3.37]} rotation={[-0.13, -0.51, -2.04]} />
          <mesh geometry={nodes.Object_2084.geometry} material={materials['Default.004']} position={[79.95, 52.27, -124.86]} rotation={[-0.29, 0.1, 1.02]} />
          <mesh geometry={nodes.Object_2085.geometry} material={materials['Default.004']} position={[22.5, 134.06, 47.04]} rotation={[-1.04, -0.66, -1.4]} />
          <mesh geometry={nodes.Object_2086.geometry} material={materials['Default.004']} position={[-108.48, -54.65, 134.44]} rotation={[-0.32, 0.51, 1.14]} />
          <mesh geometry={nodes.Object_2087.geometry} material={materials['Default.004']} position={[-170.96, -202.7, 129.03]} rotation={[-1.23, -0.64, -1.55]} />
          <mesh geometry={nodes.Object_2088.geometry} material={materials['Default.004']} position={[-88.8, -389.69, -173.64]} rotation={[-0.76, -0.6, -1.35]} />
          <mesh geometry={nodes.Object_2089.geometry} material={materials['Default.004']} position={[38.33, -218.69, -268.35]} rotation={[-0.12, -0.2, -1.17]} />
          <mesh geometry={nodes.Object_2090.geometry} material={materials['Default.004']} position={[101.68, -44.01, -242.92]} rotation={[0.31, -0.01, -0.67]} />
          <mesh geometry={nodes.Object_2091.geometry} material={materials['Default.004']} position={[116.79, 219.22, -57.01]} rotation={[-0.69, -0.74, -0.47]} />
        </group>
      </group>
      <group position={[-23.8, 14.82, 111.72]} rotation={[2.65, 0.02, -2.39]} scale={0.07}>
        <group position={[-55.41, -51.04, -46.26]}>
          <mesh geometry={nodes.Object_2080.geometry} material={materials['Default.004']} position={[-18.72, -29.85, -10.28]} rotation={[-0.06, -0.37, -1.12]} />
        </group>
      </group>
      <group position={[-20.59, 59.53, 69.55]} rotation={[1.84, -0.23, -2.61]} scale={0.07}>
        <group position={[-55.41, -51.04, -46.26]}>
          <mesh geometry={nodes.Object_2092.geometry} material={materials['Default.004']} position={[-24.2, -2.59, -5.48]} rotation={[-0.06, -0.03, 0.22]} />
          <mesh geometry={nodes.Object_2094.geometry} material={materials['Default.004']} position={[0.11, -101.42, -102.98]} />
          <mesh geometry={nodes.Object_2095.geometry} material={materials['Default.004']} position={[-56.07, -223.59, -98.93]} rotation={[-1.63, 0.32, 2.17]} />
          <mesh geometry={nodes.Object_2096.geometry} material={materials['Default.004']} position={[-142.43, -323.8, -29.28]} rotation={[-0.28, -0.51, -2.04]} />
          <mesh geometry={nodes.Object_2097.geometry} material={materials['Default.004']} position={[79.95, 52.27, -124.86]} rotation={[-0.29, 0.1, 1.02]} />
          <mesh geometry={nodes.Object_2098.geometry} material={materials['Default.004']} position={[22.5, 134.06, 47.04]} rotation={[-1.04, -0.66, -1.4]} />
          <mesh geometry={nodes.Object_2099.geometry} material={materials['Default.004']} position={[-108.48, -54.65, 134.44]} rotation={[-0.32, 0.51, 1.14]} />
          <mesh geometry={nodes.Object_2100.geometry} material={materials['Default.004']} position={[-170.96, -202.7, 129.03]} rotation={[-1.23, -0.64, -1.55]} />
          <mesh geometry={nodes.Object_2101.geometry} material={materials['Default.004']} position={[-88.8, -389.69, -173.64]} rotation={[-0.76, -0.6, -1.35]} />
          <mesh geometry={nodes.Object_2102.geometry} material={materials['Default.004']} position={[38.33, -218.69, -268.35]} rotation={[-0.12, -0.2, -1.17]} />
          <mesh geometry={nodes.Object_2103.geometry} material={materials['Default.004']} position={[101.68, -44.01, -242.92]} rotation={[0.31, -0.01, -0.67]} />
          <mesh geometry={nodes.Object_2104.geometry} material={materials['Default.004']} position={[116.79, 219.22, -57.01]} rotation={[-0.69, -0.74, -0.47]} />
          <mesh geometry={nodes.Object_2131.geometry} material={materials['Default.004']} position={[365.98, 1569.35, 154.84]} rotation={[0.19, -0.66, 0.01]} />
        </group>
      </group>
      <group position={[-21.55, 55.77, 79.96]} rotation={[1.84, -0.23, -2.61]} scale={0.07}>
        <group position={[-55.41, -51.04, -46.26]}>
          <mesh geometry={nodes.Object_2093.geometry} material={materials['Default.004']} position={[-18.72, -29.85, -10.28]} rotation={[-0.04, -0.37, -1.12]} />
        </group>
      </group>
      <group position={[-10.4, 89.81, 28.33]} rotation={[1.29, -0.42, -2.57]} scale={0.07}>
        <group position={[-55.41, -51.04, -46.26]}>
          <mesh geometry={nodes.Object_2105.geometry} material={materials['Default.004']} position={[-24.2, -2.59, -5.48]} rotation={[-0.06, -0.03, 0.22]} />
          <mesh geometry={nodes.Object_2107.geometry} material={materials['Default.004']} position={[0.11, -101.42, -102.98]} />
          <mesh geometry={nodes.Object_2108.geometry} material={materials['Default.004']} position={[-56.07, -223.59, -98.93]} rotation={[-1.63, 0.32, 2.17]} />
          <mesh geometry={nodes.Object_2109.geometry} material={materials['Default.004']} position={[-142.43, -292.97, 3.37]} rotation={[-0.13, -0.51, -2.04]} />
          <mesh geometry={nodes.Object_2110.geometry} material={materials['Default.004']} position={[79.95, 52.27, -124.86]} rotation={[-0.29, 0.1, 1.02]} />
          <mesh geometry={nodes.Object_2111.geometry} material={materials['Default.004']} position={[22.5, 134.06, 47.04]} rotation={[-1.04, -0.66, -1.4]} />
          <mesh geometry={nodes.Object_2112.geometry} material={materials['Default.004']} position={[-108.48, -54.65, 134.44]} rotation={[-0.32, 0.51, 1.14]} />
          <mesh geometry={nodes.Object_2113.geometry} material={materials['Default.004']} position={[-170.96, -202.7, 129.03]} rotation={[-1.23, -0.64, -1.55]} />
          <mesh geometry={nodes.Object_2114.geometry} material={materials['Default.004']} position={[-88.8, -389.69, -173.64]} rotation={[-0.76, -0.6, -1.35]} />
          <mesh geometry={nodes.Object_2115.geometry} material={materials['Default.004']} position={[38.33, -218.69, -268.35]} rotation={[-0.12, -0.2, -1.17]} />
          <mesh geometry={nodes.Object_2116.geometry} material={materials['Default.004']} position={[101.68, -44.01, -242.92]} rotation={[0.31, -0.01, -0.67]} />
          <mesh geometry={nodes.Object_2117.geometry} material={materials['Default.004']} position={[116.79, 219.22, -57.01]} rotation={[-0.69, -0.74, -0.47]} />
        </group>
      </group>
      <group position={[-11.96, 92.44, 39.01]} rotation={[1.29, -0.42, -2.57]} scale={0.07}>
        <group position={[-55.41, -51.04, -46.26]}>
          <mesh geometry={nodes.Object_2106.geometry} material={materials['Default.004']} position={[-18.72, -29.85, -10.28]} rotation={[-0.04, -0.37, -1.12]} />
        </group>
      </group>
      <group position={[1.58, 89.26, -27.54]} rotation={[1.29, -0.42, -2.57]} scale={0.07}>
        <group position={[-55.41, -51.04, -46.26]}>
          <mesh geometry={nodes.Object_2118.geometry} material={materials['Default.004']} position={[-24.2, -2.59, -5.48]} rotation={[-0.06, -0.03, 0.22]} />
          <mesh geometry={nodes.Object_2120.geometry} material={materials['Default.004']} position={[0.11, -101.42, -102.98]} />
          <mesh geometry={nodes.Object_2121.geometry} material={materials['Default.004']} position={[-56.07, -223.59, -98.93]} rotation={[-1.63, 0.32, 2.17]} />
          <mesh geometry={nodes.Object_2122.geometry} material={materials['Default.004']} position={[-142.43, -292.97, 3.37]} rotation={[-0.13, -0.51, -2.04]} />
          <mesh geometry={nodes.Object_2123.geometry} material={materials['Default.004']} position={[79.95, 52.27, -124.86]} rotation={[-0.29, 0.1, 1.02]} />
          <mesh geometry={nodes.Object_2124.geometry} material={materials['Default.004']} position={[22.5, 134.06, 47.04]} rotation={[-1.04, -0.66, -1.4]} />
          <mesh geometry={nodes.Object_2125.geometry} material={materials['Default.004']} position={[-108.48, -54.65, 134.44]} rotation={[-0.32, 0.51, 1.14]} />
          <mesh geometry={nodes.Object_2126.geometry} material={materials['Default.004']} position={[-170.96, -202.7, 129.03]} rotation={[-1.23, -0.64, -1.55]} />
          <mesh geometry={nodes.Object_2127.geometry} material={materials['Default.004']} position={[-88.8, -389.69, -173.64]} rotation={[-0.76, -0.6, -1.35]} />
          <mesh geometry={nodes.Object_2128.geometry} material={materials['Default.004']} position={[38.33, -218.69, -268.35]} rotation={[-0.12, -0.2, -1.17]} />
          <mesh geometry={nodes.Object_2129.geometry} material={materials['Default.004']} position={[101.68, -44.01, -242.92]} rotation={[0.31, -0.01, -0.67]} />
          <mesh geometry={nodes.Object_2130.geometry} material={materials['Default.004']} position={[116.79, 219.22, -57.01]} rotation={[-0.69, -0.74, -0.47]} />
        </group>
      </group>
      <group position={[0.01, 91.89, -16.85]} rotation={[1.29, -0.42, -2.57]} scale={0.07}>
        <group position={[-55.41, -51.04, -46.26]}>
          <mesh geometry={nodes.Object_2119.geometry} material={materials['Default.004']} position={[-18.72, -29.85, -10.28]} rotation={[-0.04, -0.37, -1.12]} />
        </group>
      </group>
      <group position={[28.35, 72.44, -73.86]} rotation={[0.69, -0.88, -2.77]} scale={0.07}>
        <group position={[-55.41, -51.04, -46.26]}>
          <mesh geometry={nodes.Object_2132.geometry} material={materials['Default.004']} position={[-24.2, -2.59, -5.48]} rotation={[-0.06, -0.03, 0.22]} />
          <mesh geometry={nodes.Object_2134.geometry} material={materials['Default.004']} position={[0.11, -101.42, -102.98]} />
          <mesh geometry={nodes.Object_2135.geometry} material={materials['Default.004']} position={[-56.07, -223.59, -98.93]} rotation={[-1.63, 0.32, 2.17]} />
          <mesh geometry={nodes.Object_2136.geometry} material={materials['Default.004']} position={[-142.43, -292.97, 3.37]} rotation={[-0.13, -0.51, -2.04]} />
          <mesh geometry={nodes.Object_2137.geometry} material={materials['Default.004']} position={[79.95, 52.27, -124.86]} rotation={[-0.29, 0.1, 1.02]} />
          <mesh geometry={nodes.Object_2138.geometry} material={materials['Default.004']} position={[22.5, 134.06, 47.04]} rotation={[-1.04, -0.66, -1.4]} />
          <mesh geometry={nodes.Object_2139.geometry} material={materials['Default.004']} position={[-108.48, -54.65, 134.44]} rotation={[-0.32, 0.51, 1.14]} />
          <mesh geometry={nodes.Object_2140.geometry} material={materials['Default.004']} position={[-170.96, -202.7, 129.03]} rotation={[-1.23, -0.64, -1.55]} />
          <mesh geometry={nodes.Object_2141.geometry} material={materials['Default.004']} position={[-88.8, -389.69, -173.64]} rotation={[-0.76, -0.6, -1.35]} />
          <mesh geometry={nodes.Object_2142.geometry} material={materials['Default.004']} position={[38.33, -218.69, -268.35]} rotation={[-0.12, -0.2, -1.17]} />
          <mesh geometry={nodes.Object_2143.geometry} material={materials['Default.004']} position={[101.68, -44.01, -242.92]} rotation={[0.31, -0.01, -0.67]} />
          <mesh geometry={nodes.Object_2144.geometry} material={materials['Default.004']} position={[116.79, 219.22, -57.01]} rotation={[-0.69, -0.74, -0.47]} />
        </group>
      </group>
      <group position={[28.17, 80.02, -65.74]} rotation={[0.69, -0.88, -2.77]} scale={0.07}>
        <group position={[-55.41, -51.04, -46.26]}>
          <mesh geometry={nodes.Object_2133.geometry} material={materials['Default.004']} position={[-18.72, -29.85, -10.28]} rotation={[-0.04, -0.37, -1.12]} />
        </group>
      </group>
      <group position={[37.95, 40.9, -119.92]} rotation={[0.31, -0.86, -2.98]} scale={0.07}>
        <group position={[-55.41, -51.04, -46.26]}>
          <mesh geometry={nodes.Object_2145.geometry} material={materials['Default.004']} position={[-24.2, -2.59, -5.48]} rotation={[-0.06, -0.03, 0.22]} />
          <mesh geometry={nodes.Object_2147.geometry} material={materials['Default.004']} position={[0.11, -101.42, -102.98]} />
          <mesh geometry={nodes.Object_2148.geometry} material={materials['Default.004']} position={[-56.07, -223.59, -98.93]} rotation={[-1.63, 0.32, 2.17]} />
          <mesh geometry={nodes.Object_2149.geometry} material={materials['Default.004']} position={[-142.43, -292.97, 3.37]} rotation={[-0.13, -0.51, -2.04]} />
          <mesh geometry={nodes.Object_2150.geometry} material={materials['Default.004']} position={[79.95, 52.27, -124.86]} rotation={[-0.29, 0.1, 1.02]} />
          <mesh geometry={nodes.Object_2151.geometry} material={materials['Default.004']} position={[22.5, 134.06, 47.04]} rotation={[-1.04, -0.66, -1.4]} />
          <mesh geometry={nodes.Object_2152.geometry} material={materials['Default.004']} position={[-108.48, -54.65, 134.44]} rotation={[-0.32, 0.51, 1.14]} />
          <mesh geometry={nodes.Object_2153.geometry} material={materials['Default.004']} position={[-170.96, -202.7, 129.03]} rotation={[-1.23, -0.64, -1.55]} />
          <mesh geometry={nodes.Object_2154.geometry} material={materials['Default.004']} position={[-88.8, -389.69, -173.64]} rotation={[-0.76, -0.6, -1.35]} />
          <mesh geometry={nodes.Object_2155.geometry} material={materials['Default.004']} position={[38.33, -218.69, -268.35]} rotation={[-0.12, -0.2, -1.17]} />
          <mesh geometry={nodes.Object_2156.geometry} material={materials['Default.004']} position={[101.68, -44.01, -242.92]} rotation={[0.31, -0.01, -0.67]} />
          <mesh geometry={nodes.Object_2157.geometry} material={materials['Default.004']} position={[116.79, 219.22, -57.01]} rotation={[-0.69, -0.74, -0.47]} />
        </group>
      </group>
      <group position={[39.34, 50, -113.69]} rotation={[0.31, -0.86, -2.98]} scale={0.07}>
        <group position={[-55.41, -51.04, -46.26]}>
          <mesh geometry={nodes.Object_2146.geometry} material={materials['Default.004']} position={[-18.72, -29.85, -10.28]} rotation={[-0.04, -0.37, -1.12]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/aster.glb')
