/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Earth() {
  const group = useRef()
  const { nodes, materials } = useGLTF('/earth.glb')
  return (
    <group ref={group} dispose={null} scale={10.8}>
      <mesh geometry={nodes.imagetostl_mesh_1.geometry} material={materials.mat0} />
      <mesh geometry={nodes.imagetostl_mesh_2.geometry} material={materials.mat1} />
    </group>
  )
}

useGLTF.preload('/earth.glb')
