/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { angleToRadians } from '../../utils/angle'

export default function Satellite() {
  const group = useRef()
  const { nodes, materials } = useGLTF('/satellite.glb')
  return (
    <group ref={group} dispose={null} scale={1} castShadow={true} position={[-20,12,-10.8]} rotation={[angleToRadians(180),0,0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, 1.28]} scale={0.02}>
          <mesh geometry={nodes.foil_gold_0.geometry} material={materials.foil_gold} />
        </group>
        <group scale={0.02}>
          <mesh geometry={nodes.foil_silver_0.geometry} material={materials.foil_silver} />
        </group>
        <group position={[0, 1.73, 0.75]} scale={0.02}>
          <mesh geometry={nodes.shiny_panels_0.geometry} material={materials.shiny_panels} />
        </group>
        <group position={[-1.73, 0, 0.75]} rotation={[0, 0, Math.PI / 2]} scale={0.02}>
          <mesh geometry={nodes.tex_01_0.geometry} material={materials.tex_01} />
        </group>
        <mesh geometry={nodes._root_0.geometry} material={materials.root_0} />
      </group>
    </group>
  )
}

useGLTF.preload('/satellite.glb')
