/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { angleToRadians } from '../../utils/angle'

export default function Ship() {
  const group = useRef()
  const { nodes, materials } = useGLTF('/ship.glb')
  return (
    <group ref={group} dispose={null} scale={0.00125} rotation={[angleToRadians(180),0,angleToRadians(165)]}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.15}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube_Material001_0.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Cube_Material002_0.geometry} material={materials['Material.005']} />
            <mesh geometry={nodes.Cube_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Cube_Material004_0.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Cube_Material_0.geometry} material={materials['Material.001']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ship.glb')
