/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { angleToRadians } from '../../utils/angle'

export default function Shuttle() {
  const group = useRef()
  const { nodes, materials } = useGLTF('/shuttle.glb')
  return (
    <group ref={group} dispose={null} scale={0.3} castShadow={true} position={[20,13,10]} rotation={[angleToRadians(30),0,angleToRadians(180)]}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.29}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Material__197} />
      </group>
    </group>
  )
}

useGLTF.preload('/shuttle.glb')
